USE ODS;

INSERT INTO ODS_DM_PROFESIONES(DE_PROFESION, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PROFESION)), current_date(), current_date()
FROM STAGE.STG_CLIENTES_CRM
WHERE LENGTH(TRIM(PROFESION))<>0;
INSERT INTO ODS_DM_PROFESIONES VALUES(9999,'DESCONOCIDO', current_date(), current_date());
INSERT INTO ODS_DM_PROFESIONES VALUES(9998,'NO APLICA', current_date(), current_date());
COMMIT;


INSERT INTO ODS_DM_CANALES (DE_CANAL, FC_INSERT,FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(CHANNEL)), NOW(), NOW()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(CHANNEL)<>'';
INSERT INTO ODS_DM_CANALES VALUES (9998, 'NO APLICA', NOW(),NOW());
INSERT INTO ODS_DM_CANALES VALUES (9999, 'DESCONOCIDO', NOW(),NOW());
COMMIT;

INSERT INTO ODS_DM_PRODUCTOS (DE_PRODUCTO, FC_INSERT, FC_MODIFICACION) 
SELECT DISTINCT UPPER(TRIM(PRODUCT_NAME)), NOW(), NOW() 
FROM STAGE.STG_PRODUCTOS_CRM 
WHERE TRIM(PRODUCT_NAME) <> ''; 
COMMIT; 
INSERT INTO ODS_DM_PRODUCTOS VALUES (9999, 'DESCONOCIDO', NOW(), NOW()); 
INSERT INTO ODS_DM_PRODUCTOS VALUES (9998, 'NO APLICA', NOW(), NOW()); 
COMMIT;

INSERT INTO ODS_DM_PAISES(DE_PAIS, FC_INSERT, FC_MODIFICACION)
(SELECT DISTINCT UPPER(TRIM(COUNTRY)), current_date(), current_date()
FROM STAGE.STG_CLIENTES_CRM
WHERE LENGTH(TRIM(COUNTRY))<>0)
UNION
(SELECT CASE WHEN (UPPER(TRIM(PRODUCT_COUNTRY))='UNITED STATES') THEN 'US' ELSE UPPER(TRIM(PRODUCT_COUNTRY)) END DE_PAIS, current_date(), current_date()
FROM STAGE.STG_PRODUCTOS_CRM
WHERE LENGTH(TRIM(PRODUCT_COUNTRY))<>0);


INSERT INTO ODS_DM_PAISES VALUES(9999,'DESCONOCIDO', current_date(), current_date());
INSERT INTO ODS_DM_PAISES VALUES(9998,'NO APLICA', current_date(), current_date());
COMMIT;

INSERT INTO ODS_DM_CIUDADES_ESTADOS(DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
(SELECT DISTINCT UPPER(TRIM(CLI.CITY)), 
UPPER(TRIM(CLI.STATE)), 
PAI.ID_PAIS,
current_date(), 
current_date()
FROM STAGE.STG_CLIENTES_CRM CLI
INNER JOIN ODS.ODS_DM_PAISES PAI ON PAI.DE_PAIS = CASE WHEN  LENGTH(TRIM(CLI.COUNTRY))<>0 THEN CLI.COUNTRY ELSE 'DESCONOCIDO' END
WHERE LENGTH(TRIM(CITY))<>0)
UNION
(SELECT DISTINCT UPPER(TRIM(PRO.PRODUCT_CITY)), 
UPPER(TRIM(PRO.PRODUCT_STATE)), 
PAI.ID_PAIS,
current_date(), 
current_date()
FROM STAGE.STG_PRODUCTOS_CRM PRO
INNER JOIN ODS.ODS_DM_PAISES PAI ON PAI.DE_PAIS = CASE WHEN  LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN PRO.PRODUCT_COUNTRY ELSE 'DESCONOCIDO' END
WHERE LENGTH(TRIM(PRO.PRODUCT_CITY))<>0);

INSERT INTO ODS_DM_CIUDADES_ESTADOS VALUES(9999,'DESCONOCIDO', 9999, 9999, current_date(), current_date());
INSERT INTO ODS_DM_CIUDADES_ESTADOS VALUES(9998,'NO APLICA', 9998, 9998, current_date(), current_date());
COMMIT;




INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION) 
SELECT DISTINCT 
CASE WHEN LENGTH(PRODUCT_CITY) <> 0 THEN UPPER(TRIM(PRODUCT_CITY)) ELSE 'DESCONOCIDO' END, 
CASE WHEN LENGTH(PRODUCT_STATE) <> 0 THEN UPPER(TRIM(PRODUCT_STATE)) ELSE 'DESCONOCIDO' END, 
PAI.ID_PAIS, 
NOW(), 
NOW() 
FROM STAGE.STG_PRODUCTOS_CRM PROD 
INNER JOIN ODS.ODS_DM_PAISES PAI ON CASE WHEN TRIM(PRODUCT_COUNTRY) <> '' THEN UPPER(REPLACE(PRODUCT_COUNTRY, 'United States', 'US')) ELSE 'DESCONOCIDO' END = PAI.DE_PAIS 
WHERE NOT EXISTS 
(SELECT 1 
FROM ODS.ODS_DM_CIUDADES_ESTADOS CIU 
WHERE CASE WHEN LENGTH(PRODUCT_CITY) <> 0 THEN UPPER(TRIM(PRODUCT_CITY)) ELSE 'DESCONOCIDO' END = CIU.DE_CIUDAD AND  
CASE WHEN LENGTH(PRODUCT_STATE) <> 0 THEN UPPER(TRIM(PRODUCT_STATE)) ELSE 'DESCONOCIDO' END = CIU.DE_ESTADO AND 
PAI.ID_PAIS = CIU.ID_PAIS); 
COMMIT; 



INSERT INTO ODS.ODS_HC_CLIENTES 
SELECT DISTINCT CUSTOMER_ID, 'DESCONOCIDO', 'DESCONOCIDO', '99-999-9999', 99, 999999, 9999999999, 
	'DESCONOCIDO', STR_TO_DATE('31/12/9999', '%d/%m/%Y'), 999, 999, NOW(), NOW() 
FROM STAGE.STG_PRODUCTOS_CRM PROD 
WHERE CUSTOMER_ID NOT IN 
(SELECT ID_CLIENTE 
FROM ODS.ODS_HC_CLIENTES); 
COMMIT; 


INSERT INTO ODS_HC_SERVICIOS 
SELECT  
PRODUCT_ID AS ID_SERVICIO, 
CASE WHEN LENGTH(TRIM(CUSTOMER_ID)) <> 0 THEN TRIM(UPPER(CUSTOMER_ID)) ELSE 'DESCONOCIDO' END ID_CLIENTE, 
PRODUCTOS.ID_PRODUCTO, 
CASE WHEN LENGTH(TRIM(ACCESS_POINT)) <> 0 THEN TRIM(UPPER(ACCESS_POINT)) ELSE 'DESCONOCIDO' END PUNTO_ACCESO, 
CANALES.ID_CANAL, 
CASE WHEN LENGTH(TRIM(AGENT_CODE)) <> 0 THEN TRIM(UPPER(AGENT_CODE)) ELSE 99999 END ID_AGENTE, 
DIR.ID_DIRECCION, 
CASE WHEN LENGTH(TRIM(START_DATE)) <> 0 THEN STR_TO_DATE(START_DATE, '%d/%m/%Y') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INICIO, 
CASE WHEN LENGTH(TRIM(INSTALL_DATE)) <> 0 THEN DATE_FORMAT(REPLACE(INSTALL_DATE, 'UTC', ''), '%Y-%m-%d') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INSTALACION, 
CASE WHEN LENGTH(TRIM(END_DATE)) <> 0 THEN DATE_FORMAT(REPLACE(END_DATE, 'UTC', ''), '%Y-%m-%d') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_FIN, 
NOW(), 
NOW() 
FROM STAGE.STG_PRODUCTOS_CRM PRO 
INNER JOIN ODS.ODS_HC_CLIENTES CLIENTES ON CASE WHEN LENGTH(TRIM(PRO.CUSTOMER_ID)) <> 0 THEN UPPER(TRIM(PRO.CUSTOMER_ID)) ELSE 'DESCONOCIDO' END = CLIENTES.ID_CLIENTE 
INNER JOIN ODS.ODS_DM_PRODUCTOS PRODUCTOS ON CASE WHEN LENGTH(TRIM(PRO.PRODUCT_NAME)) <> 0 THEN UPPER(TRIM(PRO.PRODUCT_NAME)) ELSE 'DESCONOCIDO' END = PRODUCTOS.DE_PRODUCTO 
INNER JOIN ODS.ODS_DM_CANALES CANALES ON CASE WHEN LENGTH(TRIM(PRO.CHANNEL)) <> 0 THEN UPPER(TRIM(PRO.CHANNEL)) ELSE 'DESCONOCIDO' END = CANALES.DE_CANAL 
INNER JOIN ODS.ODS_HC_DIRECCIONES DIR ON PRO.PRODUCT_ID = DIR.ID_PRODUCTO; 
COMMIT; 