USE ODS;

INSERT INTO ODS_HC_LLAMADAS (ID_IVR, TELEFONO_LLAMADA,ID_CLIENTE,FC_INICIO_LLAMADA,FC_FIN_LLAMADA,ID_DEPARTAMENTO_CC,FLG_TRANSFERIDO,ID_AGENTE_CC,FC_INSERT,FC_MODIFICACION) 
SELECT
ID
,CASE WHEN LENGTH(TRIM(PHONE_NUMBER)) <> 0 THEN TRIM(UPPER(PHONE_NUMBER)) ELSE 0 END
,9999 /*desconocido*/
,CASE WHEN LENGTH(TRIM(START_DATETIME)) <> 0 THEN DATE_FORMAT(START_DATETIME, '%Y-%m-%d') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_INICIO_LLAMADA
,CASE WHEN LENGTH(TRIM(END_DATETIME)) <> 0 THEN DATE_FORMAT(END_DATETIME, '%Y-%m-%d') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_FIN_LLAMADA
,DEP.ID_DEPARTAMENTO_CC
,CASE WHEN FLG_TRANSFER = 'True' THEN 1 ELSE 0 END FLG_TRANSFERIDO
,AGE.ID_AGENTE_CC
,NOW()
,NOW() 
FROM STAGE.STG_CONTACTOS_IVR 
INNER JOIN ODS.ODS_DM_DEPARTAMENTOS_CC DEP ON CASE WHEN LENGTH(TRIM(SERVICE)) <> 0 THEN UPPER(TRIM(SERVICE)) ELSE 'DESCONOCIDO' END = DEP.DE_DEPARTAMENTO_CC 
INNER JOIN ODS.ODS_DM_AGENTES_CC AGE ON CASE WHEN LENGTH(TRIM(AGENT)) <> 0 THEN UPPER(TRIM(AGENT)) ELSE 'DESCONOCIDO' END = AGE.DE_AGENTE_CC; 
COMMIT;

SELECT * FROM ODS.ODS_HC_LLAMADAS;